### ISSUE TITLE
Code name not terminated by new line

### ISSUE THREAD

**Issue by jakobbraun** [exasol/release-robot#28]
Considder the following example:
```
Code name: Container reuse and automatic port detection

Starting with this release the port numbers used for the test containers are read from the Exasol cluster configuration at runtime.
```

**Expected behaviour:**
Code name is `Container reuse and automatic port detection`

**Current behavior:**
Code name is `
Code name: Container reuse and automatic port detectionStarting with this release the port numbers used for the test containers are read from the Exasol cluster configuration at runtime`

**Comment by AnastasiiaSergienko** [comment]
It's a problem of Release Letter format and we currently don't support the mentioned format. 

Please follow this format for correct parsing of the release letter: https://raw.githubusercontent.com/exasol/release-robot/master/doc/user_guide/changes_file_template.md
