### ISSUE TITLE
`create` instead of `throw` in Exception producer

### ISSUE THREAD

**Issue by redcatbear** [exasol/release-robot#37]
# Situation

In

https://github.com/exasol/release-robot/blob/4c32ce7b53cfe21729fb10af94c40c36b5d35f57/src/main/java/com/exasol/repository/maven/MavenPomParser.java#L84

the message that produces an exception, only creates it, but does not throw it. Please rename the message accordingly.

**Comment by AnastasiiaSergienko** [comment]
Closed with #40
