### ISSUE TITLE
Make the ReleaseInteractor instance independent of the repository

### ISSUE THREAD

**Issue by chiaradiamarcelo** [exasol/release-robot#70]
At the moment, the way we are building a ReleaseInteractor instance hardcodes a dependency to the `repository`, through the `ReleaseMakers` and those through the `GithubAPIAdapter`.

This makes the ReleaseInteractor instance not usable in concurrent environments. We should remove this hardcoded state.

**Comment by AnastasiiaSergienko** [comment]
Closed with #72
